### ISSUE TITLE
TO logo should change text color depending on background usage

### ISSUE THREAD

**Issue by east35** [east35/TO-Educational-Landing-Page#3]

**Comment by alexbaldwin** [comment]
This is really hard to do. Welcome to dumb coding problems 101.

My suggestion would be to keep the header always dark.

**Comment by east35** [comment]
> This is really hard to do. Welcome to dumb coding problems 101.
> 
> My suggestion would be to keep the header always dark.

I'd like to avoid changing the header for each page just because of this nav thing. I've implemented a dumb solution for now. It still needs work but mostly to satisfy my OCDness.
