### ISSUE TITLE
Wow JS delayed timing

### ISSUE THREAD

**Issue by east35** [east35/TO-Educational-Landing-Page#6]
Each use of wow.js within a page needs to delay by .1 seconds

**Comment by alexbaldwin** [comment]
Wow.js animations only occur once the viewport has them in sight. So this should probably only apply to sections with multiple items you want to animate in relatively.

**Comment by alexbaldwin** [comment]
https://help.shopify.com/en/themes/liquid/tags/variable-tags#increment

**Comment by east35** [comment]
Since we're using the 'order' property to bypass Contentful post ordering, the wow.js delay increment doesn't have the desired 'cascading' effect we're looking for (animation based on html not styling order).
