### ISSUE TITLE
Home page link cards ordering

### ISSUE THREAD

**Issue by east35** [east35/TO-Educational-Landing-Page#7]
The three main cards on the home page need to be reversed ordered.

**Comment by alexbaldwin** [comment]
Flexbox has some great solves for this.

**Comment by alexbaldwin** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout/Ordering_Flex_Items

`order=4` CSS prop. i.e. `<article class="object" style="order:4">`

You make 4 a variable from Contentful. I usually this the "order override".
